//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace CoreLib.Entity
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class Device
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int DeviceGroupId { get; set; }
        [DataMember]
        public string ConnectionType { get; set; }
        [DataMember]
        public int GeneratorType { get; set; }
        [DataMember]
        public int NormalVoltage { get; set; }
        [DataMember]
        public int HighVoltage { get; set; }
        [DataMember]
        public int NormalCurrent { get; set; }
        [DataMember]
        public int HighCurrent { get; set; }
        [DataMember]
        public int HighMode { get; set; }
        [DataMember]
        public double ReseasonDate { get; set; }
        [DataMember]
        public double WorkTime { get; set; }
        [DataMember]
        public double XRayTime { get; set; }
        [DataMember]
        public double LastWorkedDate { get; set; }
        [DataMember]
        public string Name { get; set; }
        [XmlIgnore]
        public virtual DeviceGroup DeviceGroup { get; set; }
    }
}
